# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mapreduce_pb2 as mapreduce__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in mapreduce_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MapReduceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitJob = channel.unary_unary(
                '/mapreduce.MapReduceService/SubmitJob',
                request_serializer=mapreduce__pb2.JobRequest.SerializeToString,
                response_deserializer=mapreduce__pb2.JobResponse.FromString,
                _registered_method=True)
        self.ProcessMap = channel.unary_unary(
                '/mapreduce.MapReduceService/ProcessMap',
                request_serializer=mapreduce__pb2.MapTask.SerializeToString,
                response_deserializer=mapreduce__pb2.MapResult.FromString,
                _registered_method=True)
        self.ProcessReduce = channel.unary_unary(
                '/mapreduce.MapReduceService/ProcessReduce',
                request_serializer=mapreduce__pb2.ReduceTask.SerializeToString,
                response_deserializer=mapreduce__pb2.ReduceResult.FromString,
                _registered_method=True)


class MapReduceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessReduce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapReduceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=mapreduce__pb2.JobRequest.FromString,
                    response_serializer=mapreduce__pb2.JobResponse.SerializeToString,
            ),
            'ProcessMap': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessMap,
                    request_deserializer=mapreduce__pb2.MapTask.FromString,
                    response_serializer=mapreduce__pb2.MapResult.SerializeToString,
            ),
            'ProcessReduce': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessReduce,
                    request_deserializer=mapreduce__pb2.ReduceTask.FromString,
                    response_serializer=mapreduce__pb2.ReduceResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.MapReduceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mapreduce.MapReduceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MapReduceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduceService/SubmitJob',
            mapreduce__pb2.JobRequest.SerializeToString,
            mapreduce__pb2.JobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduceService/ProcessMap',
            mapreduce__pb2.MapTask.SerializeToString,
            mapreduce__pb2.MapResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessReduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.MapReduceService/ProcessReduce',
            mapreduce__pb2.ReduceTask.SerializeToString,
            mapreduce__pb2.ReduceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
